Fix printing of complex values in blade stiffened shell testing functions
smdogroup/tacs pull request #253
Opened 2023-09-22 20:37 UTC by A-CGray

@bburke38 was running into compilation errors with the latest version of clang due to some print statements involving TacsScalars that weren't written correctly to handle the complex case. This PR should fix those issues.

2023-09-22 20:39 UTC, timryanb approved these changes

2023-09-22 20:48 UTC, A-CGray commented
@bburke38 please confirm that this compiles correctly for you in complex mode before we merge

2023-09-25 04:39 UTC, bburke38 commented
I'm still running into issues in TACSBladeStiffenedShellConstitutive.cpp around line 2736. I'll see if I can suggest some edits.

2023-09-25 04:45 UTC, bburke38 requested changes
I'm not able to compile with the current version of this PR. I am in the process of making a few more changes which I will merge into this PR.

2023-09-25 04:51 UTC, bburke38 approved these changes
I can now compile in complex with the new changes.

2023-09-25 12:54 UTC, merged